choco install 7zip -y
choco install 7zip.install -y
choco install base64 -y
choco install chocolatey -y
choco install chocolatey-compatibility.extension -y
choco install chocolatey-core.extension -y
choco install chocolatey-windowsupdate.extension -y
choco install curl -y
choco install diffuse -y
choco install dotnet-6.0-runtime -y
choco install du -y
choco install eclipse -y
choco install gawk -y
choco install gimp -y
choco install go -y
choco install golang -y
choco install grep -y
choco install gzip -y
choco install KB2919355 -y
choco install KB2919442 -y
choco install KB2999226 -y
choco install KB3033929 -y
choco install KB3035131 -y
choco install KB3118401 -y
choco install kubernetes-cli -y
choco install kubernetes-helm -y
choco install less -y
choco install llvm -y
choco install Ln -y
choco install make -y
choco install miktex -y
choco install miktex.install -y
choco install mingw -y
choco install Minikube -y
choco install msedgeredirect -y
choco install mupdf -y
choco install neovim -y
choco install nvm -y
choco install nvm.install -y
choco install obs -y
choco install obs-studio -y
choco install obs-studio.install -y
choco install oh-my-posh -y
choco install openjdk -y
choco install openjdk17 -y
choco install openssh -y
choco install patch -y
choco install PowerShell -y
choco install powershell-core -y
choco install puppet -y
choco install pwsh -y
choco install python -y
choco install python3 -y
choco install ruby -y
choco install ruby.install -y
choco install rustup.install -y
choco install sed -y
choco install strawberryperl -y
choco install tree-sitter -y
choco install unzip -y
choco install vagrant -y
choco install vcredist140 -y
choco install vcredist2015 -y
choco install vcredist2017 -y
choco install vim -y
choco install virtualbox -y
choco install vlc -y
choco install vlc.install -y
choco install Wget -y
choco install which -y
choco install windirstat -y
choco install wireshark -y
